### ISSUE TITLE
IP-Grabber

### ISSUE THREAD

**Issue by Sn8ow** [NoelP-YouTube/TikTok-Viewbot#2]
Hi, I wanted to let you know this tool is dangerous as I was fighting NoelP and later had a Ddos attack on my IP from it

**Comment by NoelP-YouTube** [comment]
In the Terms of Service is stated, that we may use your personal data to improve experience. This is also for blacklisting matters. I am not dangerous at all, You however are.. Your Tiktok tool YOU have uploaded includes rats considering its making requests to CreateProcessW and GetSystemDirectoryW. I'm not involved with your internet outages... You didn't read the terms of service and it struck you. Fuck, Off.. :))
